### ISSUE TITLE
SRPMs?

### ISSUE THREAD

**Issue by bish0polis** [Wakeful-Cloud/pam-oauth#43]
I see RPMs in the releases.  But I'm a little nervous.  The chain of validation from source to artifact isn't *verifiably* sound. 

Are you producing SRPMs that you're not showing in the releases?  Can we have them built and published as well so we can trivially reproduce the build and compare checksums?

Thanks!

**Comment by Wakeful-Cloud** [comment]
> Are you producing SRPMs that you're not showing in the releases?

Nope - I'm not a regular RHEL/Fedora user, so I did not know they existed until your post. The build artifacts are all produced by `nfpm` via GitHub actions.

> Can we have them built and published as well so we can trivially reproduce the build and compare checksums?

I can definitely look into generating SRPMs (in addition to a litany of other improvements, including rewriting everything in Rust, automated unit tests, signing releases, including SBOMs in releases, etc.), but I'm very, very busy at the moment, so it may be a bit until I can take a look (If you'd like to open a PR, I'm happy to review it). I would encourage you to download this repository and build from source in the meantime.

**Comment by Wakeful-Cloud** [comment]
I've looked a bit more into it and I'm not sure this will be possible with NFPM since they do not support SRPM files (https://github.com/goreleaser/nfpm/issues/275). Perhaps a Dockerfile that builds everything from source would be a suitable workaround (since I'd like to avoid adding any distro-specific functionality to the build process, if possible)? I'm going to close this for now, but we can revisit this in the future - I agree that this is an area for improvement.

**Comment by bish0polis** [comment]
> the whole point of nfpm to not have to deal with rpm specs 
-- https://github.com/goreleaser/nfpm/issues/27_5#issuecomment-756334366

I saw this and I think I've hit my limit for stunned naivete.  Would that they knew firing all the mentors and gurus in post-y2k would lead to this "all fire, no smoke alarms" style of development ... you know they'd do it anyway.  It's still sad to see.

I'm always on a deep dive, and only came to Periscope when I saw this note.  I have a half-assed plan to build the (S)RPM myself, which is usually straightforward, but code can have delightfully different 'compatibility' with RPM-building, and modern, squishy, supply-chain-slut paradigms are the more variable.

I won't be using dockers, but go ahead -- security and validation, again, more a hrSWInstalledTable thing.

> I can definitely look into generating SRPMs (in addition to a litany of other improvements, including rewriting everything in Rust, automated unit tests, signing releases, including SBOMs in releases, etc.), but

Nope.  Don't rewrite in Rust just for funzies or peer pressure, DO consider unit tests and signing if they're actually interesting, do the SBOM (but see if that's easier in RPM-land);  but of course only do the things that scratch the itch you have; and I know that impacts my goals here too!

Let me clear my own litany (so little coding in my hot list, and I don't do Go yet), and I'll see if I can get time in on this vs the secondary litany like we all have.  

Close this.  Come back on it later if you see it.  Get some egg-nog, get some rest, see people, touch some snow, etc.  Be well.

**Comment by Wakeful-Cloud** [comment]
I appreciate that haha! I've been planning on rewriting in Rust for quite some time, prior to this repo being open-sourced to remove the C shim (Go's runtime doesn't play well with `dlopen` and I don't love the extra potential for vulnerabilities. Have a great holiday too!
